### ISSUE TITLE
Error when using your pretrained language model for the 10kGNAD data

### ISSUE THREAD

**Issue by Dude43** [jfilter/ulmfit-for-german#1]
Hey,
unfortunately, I am getting the following error when running your exemplary code for the 10kGNAD data set. It occurs when loading the model (learn_lm.load('ulmfit_for_german_jfilter')). I hope you can help me.

Best, Jacob

RuntimeError: Error(s) in loading state_dict for SequentialRNN:
	size mismatch for 0.rnns.0.weight_hh_l0_raw: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.0.module.weight_ih_l0: copying a param with shape torch.Size([4600, 400]) from checkpoint, the shape in current model is torch.Size([4608, 400]).
	size mismatch for 0.rnns.0.module.weight_hh_l0: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.0.module.bias_ih_l0: copying a param with shape torch.Size([4600]) from checkpoint, the shape in current model is torch.Size([4608]).
	size mismatch for 0.rnns.0.module.bias_hh_l0: copying a param with shape torch.Size([4600]) from checkpoint, the shape in current model is torch.Size([4608]).
	size mismatch for 0.rnns.1.weight_hh_l0_raw: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.1.module.weight_ih_l0: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.1.module.weight_hh_l0: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.1.module.bias_ih_l0: copying a param with shape torch.Size([4600]) from checkpoint, the shape in current model is torch.Size([4608]).
	size mismatch for 0.rnns.1.module.bias_hh_l0: copying a param with shape torch.Size([4600]) from checkpoint, the shape in current model is torch.Size([4608]).
	size mismatch for 0.rnns.2.module.weight_ih_l0: copying a param with shape torch.Size([1600, 1150]) from checkpoint, the shape in current model is torch.Size([1600, 1152]).

**Comment by jfilter** [comment]
There is yet another breaking change with the FastAI lib. There seem to be a work around though: https://forums.fast.ai/t/ulmfit-german/22529/106

**Comment by ismailbbm** [comment]
The workaround is not complete. However the following has worked for me:
`   
config = awd_lstm_lm_config.copy() 
config['n_hid'] = 1150 
learn_lm = language_model_learner(data_lm, AWD_LSTM, drop_mult=0.5, pretrained=False, config=config)
 learn_lm.load('ulmfit_for_german_jfilter')`

**Comment by Karl-Haurenherm** [comment]
Hey guys!

I ran into the same error as Jacob and could fix it thanks to Ismails workaround.
But then, further down the notebook, when creating a new learner object

_learn = text_classifier_learner(data_train, AWD_LSTM, drop_mult=0.5)
learn.load_encoder('enc')_

I get the same error again. 
This time, the workaround does not help.
Can you guys help?

Kind regards,
Karl

**Comment by jfilter** [comment]
Yes, you are right. Thanks.

```python
config = awd_lstm_lm_config.copy()
config['n_hid'] = 1150
learn_lm = language_model_learner(data_lm, AWD_LSTM, drop_mult=0.5, pretrained=False, config=config)
learn_lm.load('ulmfit_for_german_jfilter')
```
