### ISSUE TITLE
Any chance to share a predict statement of your classifier?

### ISSUE THREAD

**Issue by ismailbbm** [jfilter/ulmfit-for-german#2]
Thank you for your pretrained language model!

When trying to evaluate individual inputs, I get:

`KeyError: tensor(0)`

I tried multiple syntax but the one that I would have expected to work is this one:

`learn.predict(df_train['text'].iloc[0])`

**Comment by ismailbbm** [comment]
Did not manage to solve this. Used the method `get_preds` instead

**Comment by Jiejiang1996** [comment]
You have to convert  itos to list, not a dict.
